### ISSUE TITLE
Cannot install gem on Windows (latest Ruby)

### ISSUE THREAD

**Issue by stibra** [soffes/pngdefry#5]
Cannot install this gem on Windows, any plans for binaries for Windows or instructions how to install it on Windows?

**Comment by lukajandric** [comment]
It's seems to be known issue with changes in Mingw (extern for __forceinline).
See:
https://github.com/nothings/stb/issues/116
https://github.com/creationix/dukluv/issues/25

So
https://github.com/soffes/pngdefry/blob/master/ext/pngdefry/miniz.c#L885-L891
should be more like
https://github.com/creationix/dukluv/blob/master/lib/miniz.c#L882-L893
